name: 'Environment Bootstrapping'
description: 'Environment bootstrapping for subsequent action calls'

inputs:
  go-version:
    description: 'Go version - <CURRENT> uses go.mod one'
    required: true
    default: '<CURRENT>'

  timeout:
    description: 'Timeout (per step)'
    required: true
    default: '5m'

runs:
  using: 'composite'
  steps:
    - name: Bootstrap Environment
      shell: bash
      run: |
        # environment bootstrapping (general purpose actions required envs)
        
        # get current branch
        GWY_BRANCH=$(git branch --show-current)
        echo "GWY_BRANCH=$GWY_BRANCH" >> $GITHUB_ENV
        echo "application branch: $GWY_BRANCH" >&2
        
        # parse app name from go.mod
        GWY_APP=$(grep '^module ' go.mod | awk '{print $2}' | sed 's|.*/||')
        echo "GWY_APP=$GWY_APP" >> $GITHUB_ENV
        echo "application name (from go.mod): $GWY_APP" >&2
        
        # determine environment go version
        
        if [ "${{ inputs.go-version }}" = "<CURRENT>" ]; then
          GWY_GO_VERSION=$(grep '^go ' go.mod | awk '{print $2}')
          echo "go version (from go.mod): $GWY_GO_VERSION" >&2
        else
          GWY_GO_VERSION="${{ inputs.go-version }}"
          echo "go version (user supplied): $GWY_GO_VERSION" >&2
        fi
        
        echo "GWY_GO_VERSION=$GWY_GO_VERSION" >> $GITHUB_ENV
        
        # parse app version from branch
        
        if [[ "$GWY_BRANCH" =~ ^release/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          GWY_APP_VERSION=$(echo "$GWY_BRANCH" | sed 's|^release/||')
        elif [[ "$GWY_BRANCH" =~ / ]]; then
          GWY_APP_VERSION=$(echo "$GWY_BRANCH" | sed 's|.*/||')
        else
          GWY_APP_VERSION="$GWY_BRANCH"
        fi
        
        echo "application version: $GWY_APP_VERSION" >&2
        echo "GWY_APP_VERSION=$GWY_APP_VERSION" >> $GITHUB_ENV
        
        # process steps timeout
        
        GWY_TIMEOUT_SECONDS=$(echo "${{ inputs.timeout }}" | sed 's/m/*60/;s/h/*3600/;s/d/*86400/' | bc)
        echo "GWY_TIMEOUT_SECONDS=$GWY_TIMEOUT_SECONDS" >> $GITHUB_ENV 

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GWY_GO_VERSION }}